<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Employee;
use App\Models\User;
use App\Models\Role;
use Carbon\Carbon;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $employeeRole = Role::where('slug', 'employee')->first();
        $hrRole = Role::where('slug', 'hr')->first();
        $accountsRole = Role::where('slug', 'accounts')->first();

        $employees = [
            [
                'employee_type' => 'Permanent',
                'full_name' => 'Rajesh Kumar',
                'father_mother_name' => 'Suresh Kumar',
                'dob' => Carbon::parse('1990-05-15'),
                'gender' => 'Male',
                'mobile_number' => '9876543210',
                'email' => 'rajesh.kumar@hrms.com',
                'address' => '123 Main Street, New Delhi',
                'department' => 'IT',
                'designation' => 'Senior Software Developer',
                'date_of_joining' => Carbon::parse('2020-01-15'),
                'employment_status' => 'Active',
                'status' => 'active',
            ],
            [
                'employee_type' => 'Permanent',
                'full_name' => 'Priya Sharma',
                'father_mother_name' => 'Ramesh Sharma',
                'dob' => Carbon::parse('1992-08-22'),
                'gender' => 'Female',
                'mobile_number' => '9876543211',
                'email' => 'priya.sharma@hrms.com',
                'address' => '456 Park Avenue, Mumbai',
                'department' => 'HR',
                'designation' => 'HR Manager',
                'date_of_joining' => Carbon::parse('2019-06-01'),
                'employment_status' => 'Active',
                'status' => 'active',
            ],
            [
                'employee_type' => 'Contract',
                'full_name' => 'Amit Patel',
                'father_mother_name' => 'Kiran Patel',
                'dob' => Carbon::parse('1988-11-10'),
                'gender' => 'Male',
                'mobile_number' => '9876543212',
                'email' => 'amit.patel@hrms.com',
                'address' => '789 Business Park, Bangalore',
                'department' => 'Finance',
                'designation' => 'Financial Analyst',
                'date_of_joining' => Carbon::parse('2023-03-01'),
                'employment_status' => 'Contract',
                'contract_start_date' => Carbon::parse('2023-03-01'),
                'contract_end_date' => Carbon::parse('2024-02-28'),
                'status' => 'active',
            ],
            [
                'employee_type' => 'Permanent',
                'full_name' => 'Sneha Reddy',
                'father_mother_name' => 'Venkatesh Reddy',
                'dob' => Carbon::parse('1995-03-18'),
                'gender' => 'Female',
                'mobile_number' => '9876543213',
                'email' => 'sneha.reddy@hrms.com',
                'address' => '321 Tech Hub, Hyderabad',
                'department' => 'Marketing',
                'designation' => 'Marketing Executive',
                'date_of_joining' => Carbon::parse('2021-07-10'),
                'employment_status' => 'Active',
                'status' => 'active',
            ],
            [
                'employee_type' => 'Permanent',
                'full_name' => 'Vikram Singh',
                'father_mother_name' => 'Harpreet Singh',
                'dob' => Carbon::parse('1987-09-25'),
                'gender' => 'Male',
                'mobile_number' => '9876543214',
                'email' => 'vikram.singh@hrms.com',
                'address' => '654 Corporate Tower, Pune',
                'department' => 'Operations',
                'designation' => 'Operations Manager',
                'date_of_joining' => Carbon::parse('2018-04-20'),
                'employment_status' => 'Active',
                'status' => 'active',
            ],
            [
                'employee_type' => 'Contract',
                'full_name' => 'Anjali Mehta',
                'father_mother_name' => 'Ravi Mehta',
                'dob' => Carbon::parse('1993-12-05'),
                'gender' => 'Female',
                'mobile_number' => '9876543215',
                'email' => 'anjali.mehta@hrms.com',
                'address' => '987 Innovation Center, Chennai',
                'department' => 'IT',
                'designation' => 'UI/UX Designer',
                'date_of_joining' => Carbon::parse('2023-01-15'),
                'employment_status' => 'Contract',
                'contract_start_date' => Carbon::parse('2023-01-15'),
                'contract_end_date' => Carbon::parse('2023-12-31'),
                'status' => 'active',
            ],
            [
                'employee_type' => 'Permanent',
                'full_name' => 'Rahul Verma',
                'father_mother_name' => 'Sunil Verma',
                'dob' => Carbon::parse('1991-07-30'),
                'gender' => 'Male',
                'mobile_number' => '9876543216',
                'email' => 'rahul.verma@hrms.com',
                'address' => '147 Software Park, Noida',
                'department' => 'IT',
                'designation' => 'DevOps Engineer',
                'date_of_joining' => Carbon::parse('2020-09-01'),
                'employment_status' => 'Active',
                'status' => 'active',
            ],
            [
                'employee_type' => 'Permanent',
                'full_name' => 'Kavita Nair',
                'father_mother_name' => 'Suresh Nair',
                'dob' => Carbon::parse('1994-04-12'),
                'gender' => 'Female',
                'mobile_number' => '9876543217',
                'email' => 'kavita.nair@hrms.com',
                'address' => '258 Business Center, Kochi',
                'department' => 'HR',
                'designation' => 'HR Executive',
                'date_of_joining' => Carbon::parse('2022-02-15'),
                'employment_status' => 'Active',
                'status' => 'active',
            ],
            [
                'employee_type' => 'Permanent',
                'full_name' => 'Mohammed Ali',
                'father_mother_name' => 'Ibrahim Ali',
                'dob' => Carbon::parse('1989-06-20'),
                'gender' => 'Male',
                'mobile_number' => '9876543218',
                'email' => 'mohammed.ali@hrms.com',
                'address' => '369 Trade Center, Ahmedabad',
                'department' => 'Finance',
                'designation' => 'Accountant',
                'date_of_joining' => Carbon::parse('2019-11-10'),
                'employment_status' => 'Active',
                'status' => 'active',
            ],
            [
                'employee_type' => 'Contract',
                'full_name' => 'Divya Iyer',
                'father_mother_name' => 'Krishnan Iyer',
                'dob' => Carbon::parse('1996-10-08'),
                'gender' => 'Female',
                'mobile_number' => '9876543219',
                'email' => 'divya.iyer@hrms.com',
                'address' => '741 Tech Valley, Bangalore',
                'department' => 'Marketing',
                'designation' => 'Digital Marketing Specialist',
                'date_of_joining' => Carbon::parse('2023-05-01'),
                'employment_status' => 'Contract',
                'contract_start_date' => Carbon::parse('2023-05-01'),
                'contract_end_date' => Carbon::parse('2024-04-30'),
                'status' => 'active',
            ],
            [
                'employee_type' => 'Permanent',
                'full_name' => 'Suresh Yadav',
                'father_mother_name' => 'Ram Yadav',
                'dob' => Carbon::parse('1986-02-14'),
                'gender' => 'Male',
                'mobile_number' => '9876543220',
                'email' => 'suresh.yadav@hrms.com',
                'address' => '852 Industrial Area, Gurgaon',
                'department' => 'Operations',
                'designation' => 'Operations Executive',
                'date_of_joining' => Carbon::parse('2017-08-20'),
                'employment_status' => 'Active',
                'status' => 'active',
            ],
            [
                'employee_type' => 'Permanent',
                'full_name' => 'Meera Joshi',
                'father_mother_name' => 'Prakash Joshi',
                'dob' => Carbon::parse('1992-01-28'),
                'gender' => 'Female',
                'mobile_number' => '9876543221',
                'email' => 'meera.joshi@hrms.com',
                'address' => '963 Residential Complex, Jaipur',
                'department' => 'IT',
                'designation' => 'QA Engineer',
                'date_of_joining' => Carbon::parse('2021-03-15'),
                'employment_status' => 'Active',
                'status' => 'active',
            ],
            [
                'employee_type' => 'Permanent',
                'full_name' => 'Arjun Malhotra',
                'father_mother_name' => 'Rajesh Malhotra',
                'dob' => Carbon::parse('1990-09-16'),
                'gender' => 'Male',
                'mobile_number' => '9876543222',
                'email' => 'arjun.malhotra@hrms.com',
                'address' => '159 Corporate Plaza, Chandigarh',
                'department' => 'Sales',
                'designation' => 'Sales Manager',
                'date_of_joining' => Carbon::parse('2020-06-01'),
                'employment_status' => 'Active',
                'status' => 'active',
            ],
            [
                'employee_type' => 'Contract',
                'full_name' => 'Pooja Desai',
                'father_mother_name' => 'Mahesh Desai',
                'dob' => Carbon::parse('1994-07-22'),
                'gender' => 'Female',
                'mobile_number' => '9876543223',
                'email' => 'pooja.desai@hrms.com',
                'address' => '357 Startup Hub, Surat',
                'department' => 'IT',
                'designation' => 'Frontend Developer',
                'date_of_joining' => Carbon::parse('2023-02-01'),
                'employment_status' => 'Contract',
                'contract_start_date' => Carbon::parse('2023-02-01'),
                'contract_end_date' => Carbon::parse('2024-01-31'),
                'status' => 'active',
            ],
            [
                'employee_type' => 'Permanent',
                'full_name' => 'Nikhil Gupta',
                'father_mother_name' => 'Amit Gupta',
                'dob' => Carbon::parse('1988-12-03'),
                'gender' => 'Male',
                'mobile_number' => '9876543224',
                'email' => 'nikhil.gupta@hrms.com',
                'address' => '468 Business District, Lucknow',
                'department' => 'Finance',
                'designation' => 'Finance Manager',
                'date_of_joining' => Carbon::parse('2018-10-15'),
                'employment_status' => 'Active',
                'status' => 'active',
            ],
            [
                'employee_type' => 'Permanent',
                'full_name' => 'Ritu Agarwal',
                'father_mother_name' => 'Vikram Agarwal',
                'dob' => Carbon::parse('1993-05-19'),
                'gender' => 'Female',
                'mobile_number' => '9876543225',
                'email' => 'ritu.agarwal@hrms.com',
                'address' => '579 Tech Park, Indore',
                'department' => 'HR',
                'designation' => 'Recruitment Specialist',
                'date_of_joining' => Carbon::parse('2021-11-01'),
                'employment_status' => 'Active',
                'status' => 'active',
            ],
            [
                'employee_type' => 'Permanent',
                'full_name' => 'Karan Thakur',
                'father_mother_name' => 'Ramesh Thakur',
                'dob' => Carbon::parse('1991-08-27'),
                'gender' => 'Male',
                'mobile_number' => '9876543226',
                'email' => 'karan.thakur@hrms.com',
                'address' => '680 Innovation Zone, Bhopal',
                'department' => 'IT',
                'designation' => 'Backend Developer',
                'date_of_joining' => Carbon::parse('2020-04-10'),
                'employment_status' => 'Active',
                'status' => 'inactive',
            ],
            [
                'employee_type' => 'Contract',
                'full_name' => 'Shreya Banerjee',
                'father_mother_name' => 'Amit Banerjee',
                'dob' => Carbon::parse('1995-11-14'),
                'gender' => 'Female',
                'mobile_number' => '9876543227',
                'email' => 'shreya.banerjee@hrms.com',
                'address' => '791 Commercial Street, Kolkata',
                'department' => 'Marketing',
                'designation' => 'Content Writer',
                'date_of_joining' => Carbon::parse('2023-06-15'),
                'employment_status' => 'Contract',
                'contract_start_date' => Carbon::parse('2023-06-15'),
                'contract_end_date' => Carbon::parse('2024-06-14'),
                'status' => 'active',
            ],
            [
                'employee_type' => 'Permanent',
                'full_name' => 'Aditya Rao',
                'father_mother_name' => 'Srinivas Rao',
                'dob' => Carbon::parse('1989-03-09'),
                'gender' => 'Male',
                'mobile_number' => '9876543228',
                'email' => 'aditya.rao@hrms.com',
                'address' => '802 Business Square, Visakhapatnam',
                'department' => 'Operations',
                'designation' => 'Logistics Coordinator',
                'date_of_joining' => Carbon::parse('2019-05-20'),
                'employment_status' => 'Active',
                'status' => 'active',
            ],
            [
                'employee_type' => 'Permanent',
                'full_name' => 'Neha Kapoor',
                'father_mother_name' => 'Ravi Kapoor',
                'dob' => Carbon::parse('1992-06-25'),
                'gender' => 'Female',
                'mobile_number' => '9876543229',
                'email' => 'neha.kapoor@hrms.com',
                'address' => '913 Corporate Avenue, Ludhiana',
                'department' => 'Sales',
                'designation' => 'Sales Executive',
                'date_of_joining' => Carbon::parse('2022-01-10'),
                'employment_status' => 'Active',
                'status' => 'active',
            ],
        ];

        foreach ($employees as $index => $employeeData) {
            // Generate employee ID
            $employeeId = Employee::generateEmployeeId();
            
            // Create employee
            $employee = Employee::create([
                'employee_id' => $employeeId,
                'employee_type' => $employeeData['employee_type'],
                'full_name' => $employeeData['full_name'],
                'father_mother_name' => $employeeData['father_mother_name'],
                'dob' => $employeeData['dob'],
                'gender' => $employeeData['gender'],
                'mobile_number' => $employeeData['mobile_number'],
                'email' => $employeeData['email'],
                'address' => $employeeData['address'],
                'department' => $employeeData['department'],
                'designation' => $employeeData['designation'],
                'date_of_joining' => $employeeData['date_of_joining'],
                'employment_status' => $employeeData['employment_status'],
                'contract_start_date' => $employeeData['contract_start_date'] ?? null,
                'contract_end_date' => $employeeData['contract_end_date'] ?? null,
                'status' => $employeeData['status'],
            ]);

            // Optionally link to user account (for some employees)
            // For demonstration, we'll skip linking to keep it simple
            // You can uncomment below to link some employees to user accounts
            /*
            if ($index < 5 && $employeeRole) {
                $user = User::where('email', $employeeData['email'])->first();
                if (!$user) {
                    $user = User::create([
                        'name' => $employeeData['full_name'],
                        'username' => strtolower(str_replace(' ', '.', $employeeData['full_name'])),
                        'email' => $employeeData['email'],
                        'password' => Hash::make('password'),
                        'role_id' => $employeeRole->id,
                        'status' => 'active',
                    ]);
                }
                $employee->update(['user_id' => $user->id]);
            }
            */
        }

        $this->command->info('20 employee records created successfully!');
    }
}
